Once you have an asset or an asset group defined, it's simple to request that it be included whenever that page or block is rendered.

=== Requiring an Asset Group from within a Page Type Controller or Page Controller.

Make sure this code exists within your page type or single page controller.

[source,php]
----
public function view()
{
    $this->requireAsset('mediaelement');
}
----

=== Requiring a Single Asset from within a Controller

Make sure this code exists within your page type or single page controller.

[source,php]
----
public function view()
{
    $this->requireAsset('javascript', 'jquery');
}
----

=== Requiring an Asset Group within the "add" interface of a block

Make sure this code exists within your block controller.

[source,php]
----
public function add()
{
    $this->requireAsset('core/filemanager');
}
----

=== Requiring an Asset Group when viewing a particular block

Make sure this code exists within your block controller.

[source,php]
----
public function registerViewAssets()
{
    $this->requireAsset('mediaelement');
}
----

=== Requiring or Marking an Asset as Provided in a Theme

This information is available in the theme documentation:

* http://www.concrete5.org/developers-book/designing-for-concrete5/advanced-css-and-javascript-usage/requiring-core-javascript-or-css-in-a-theme/[Requiring Core JavaScript or CSS in a Theme]
* http://www.concrete5.org/developers-book/designing-for-concrete5/advanced-css-and-javascript-usage/overriding-or-providing-core-javascript-or-css-in-a-theme/[Overriding or Providing Core JavaScript or CSS in a Theme]

link:/developers-book/assets/asset-list/[Built-in Asset List »]

link:/developers-book/assets/grouping-assets/[« Grouping Assets]
